---
name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build image
        run: docker build -t "cr.yandex/crp6s12nuv1e43akkgok/catgpt:v2.0" .
      # - name: Log in to Docker Hub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker push cr.yandex/crp6s12nuv1e43akkgok/catgpt:v2.0

